version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/app
      - ./vendor:/app/vendor
      - ./node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    env_file:
      - .env
    command: >
      sh -c "
      ./wait-for-it.sh db:5432 -- php artisan migrate --force &&
      php-fpm
      "
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laravel-dc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/app/public
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data: